pipeline{
    agent any

    tools{
        maven "mvn"
    }

    stages{

        stage('Git Checkout'){
            steps{

            git 'https://github.com/codewithz/dxc-web-app.git'
            }
        }

        stage('Maven Build'){
            steps{
            bat """
                cd mywebapp
                mvn clean package
            """
            }
        }

    }
}
