pipeline{

    
    agent any

    environment{
        jarLocation='C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\maven-deploy1\\target\\my-app-1.0-SNAPSHOT.jar'

    }

    tools{

        maven "mvn"
    }

    stages{

        stage('Build'){

            steps{
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'

                bat 'mvn clean test package'

            }
        }

    }
    post{
        success{
            bat 'java -jar %jarLocation%'
        }
    }
}
