pipeline{
    agent any

    tools{
        maven "mvn"
    }
    environment{
        tomcatWebLocation="\"C:\\Users\\gkumar22\\Downloads\\apache-tomcat-9.0.55\\apache-tomcat-9.0.55\\webapps\""
        tomcatBinLocation="\"C:\\Users\\gkumar22\\Downloads\\apache-tomcat-9.0.55\\apache-tomcat-9.0.55\\bin\""
        buildLocation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\maven-deploy\\mywebapp\\target\\mywebapp.war"

    }

    stages{

        stage('Git Checkout'){
            steps{

            git 'https://github.com/codewithz/dxc-web-app.git'
            }
        }

        stage('Maven Build'){
            steps{
            bat """
                cd mywebapp
                mvn clean package
            """
            }
        }

    }

    post{
        success{

            bat """
                copy %buildLocation%  %tomcatWebLocation%
                %tomcatBinLocation%\\startup.bat
            """

        }
    }
}
